config/routes.rb
Crickytube::Application.routes.draw do
  resources :user
  get "user/new"

  get "pages/recent"

  get "pages/popular"

  get "pages/crickytube"

  get "pages/fanfights"

  get "pages/livelinks"

  get "pages/highlights"

  match "/signup", :to=>"user#new"
  match "/recent", :to => "pages#recent"
  match "/popular", :to => "pages#popular"
  match "/crickytube", :to => "pages#crickytube"
  match "/fanfights", :to => "pages#fanfights"
  match "/livelinks", :to => "pages#livelinks"
  match "/highlights", :to => "pages#highlights"
  match "/", :to =>"pages#recent"
  root :to=>"pages#recent"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
 attr_accessible :name, :email
 validates :name, :presence =>true
 validates :email, :presence => true

 validates :password, :presence =>true,

 befor_save :encrypt_password
 private
  def encrypt_password
	self.encrypted_password = encrypt(password)
  end
  def encrypt(string)
	string
  end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def recent
  	@title ="recent"
  end

  def popular
 	@title ="popular"
  end

  def crickytube
 	@title = "crickytube"
  end

  def fanfights
	@title ="fanfights"
  end

  def livelinks
	@title ="livelinks"
  end

  def highlights
	@title ="highlights"
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
   @user = User.find(params[:id])
  end
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Crickytube | <%=@title%></title>
  			<%= stylesheet_link_tag :all %>
 			<%= javascript_include_tag :defaults %>
  			<%= csrf_meta_tag %>
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
				<div id="logo">
					<img src="http://i.imgur.com/r3SOE.png"/>
				</div>
				<nav id="navs">
					<ul>
						<li><%= link_to "Recent", recent_path %></li>
						<li><%= link_to "Popular",popular_path%></li>
						<li><%= link_to "CrickyTube", crickytube_path%></li>
						<li><%= link_to "Fan-Fights", fanfights_path%></li>
						<li><%= link_to "Live Links", livelinks_path%></li>
						<li><%= link_to "Highlights",highlights_path%></li>
					</ul>
			</div>
			<div id="mainarea">
					<%= yield %>
			</div>
			<div id="footer">
				<div id="footInfo">
					crickytube.com
				</div>
			</div>
		</div>
	</body>
</html>

app/views/pages/crickytube.html.erb
<h1>Pages#crickytube</h1>
<p>Find me in app/views/pages/crickytube.html.erb</p>

app/views/pages/fanfights.html.erb
<h1>Pages#fanfights</h1>
<p>Find me in app/views/pages/fanfights.html.erb</p>

app/views/pages/highlights.html.erb
<h1>Pages#highlights</h1>
<p>Find me in app/views/pages/highlights.html.erb</p>

app/views/pages/livelinks.html.erb
<h1>Pages#livelinks</h1>
<p>Find me in app/views/pages/livelinks.html.erb</p>

app/views/pages/popular.html.erb
<h1>Pages#popular</h1>
<p>Find me in app/views/pages/popular.html.erb</p>

app/views/pages/recent.html.erb
<h1>Pages#recent</h1>
<p>Find me in app/views/pages/recent.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<div class="userInfo">
<%= @user.name %>, <%= @user.email%>
</div>